version: '3.7'
services:

  loki:
    image: grafana/loki:latest
    restart: always
    container_name: loki
    ports:
      - 3100:3100

  prometheus:
    container_name: prometheus
    restart: always
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  promtail:
    container_name: promtail
    restart: always
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log

  grafana:
    container_name: grafana
    restart: always
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki

  jaeger-all-in-one:
    container_name: jaeger 
    restart: always  
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"      
  
  otel-collector:
    container_name: otel-collector
    restart: always
    image: otel/opentelemetry-collector-contrib:0.76.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - loki 
  #redis:
  #  container_name: redis  
  #  restart: always
  #  image: redis:6.2
  #  ports:
  #    - "6379:6379"    
  #rabbitmq:
  #  container_name: rabbitmq
  #  restart: always
  #  image: rabbitmq:3.9.13-management
  #  ports:
  #    - "15672:15672"
  #    - "5672:5672"    
volumes:
  grafana_data:    
  mongodb_data:   

                 