name: SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '16 22 * * 3'

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu' 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          cd src
          dotnet tool restore && dotnet restore
          dotnet sonarscanner begin  \
          /k:jcmdsbr_otel-sample-dotnet"  \
          /o:"jcmdsbr \ 
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
          dotnet build .\Otel.Sample.App.sln \
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
