name: SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '16 22 * * 3'

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: bash
        run: |
          cd src
          apt-get update &&  apt-get install -y openjdk-11-jdk && dotnet tool restore && dotnet restore .\Otel.Sample.App.sln \
          dotnet sonarscanner begin  \
          /k:"jcmdsbr_otel-sample-dotnet"  \
          /o:"jcmdsbr" \ 
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
          dotnet build .\Otel.Sample.App.sln \
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
